version: '3.5'
services:
  etcd1:
    build: db
    privileged: true
    container_name: node1
    hostname: node1
    tmpfs: /etcd/mem
    networks:
      - perseus
  etcd2:
    build: db
    privileged: true
    container_name: node2
    hostname: node2
    tmpfs: /etcd/mem
    networks:
      - perseus
  etcd3:
    build: db
    privileged: true
    container_name: node3
    hostname: node3
    tmpfs: /etcd/mem
    networks:
      - perseus
networks:
  perseus:
    driver: bridge
    name: perseus