version: '3'
services:
  gryadka1:
    build: db
    privileged: true
    container_name: node1
    hostname: node1
    tmpfs: /gryadka/mem
    networks:
      - perseus
  gryadka2:
    build: db
    privileged: true
    container_name: node2
    hostname: node2
    tmpfs: /gryadka/mem
    networks:
      - perseus
  gryadka3:
    build: db
    privileged: true
    container_name: node3
    hostname: node3
    tmpfs: /gryadka/mem
    networks:
      - perseus
networks:
  perseus:
    driver: bridge